### ISSUE TITLE
Print displayed QR Code

### ISSUE THREAD

**Issue by anistark** [anistark/qrgen#2]
Add functionality to print or download the displayed QR Code in PDF or image (png/jpg) formats.

**Comment by eudanilolira** [comment]
I can help you with that

**Comment by anistark** [comment]
By all means, feel free to take it up.
The changes to be made in [/editor.html](https://qrgen.dev/editor).

**Comment by eudanilolira** [comment]
It's done for PNG, i will do a PR

**Comment by anistark** [comment]
Great job @DaniloLira. Merged it. Thanks 👍
