### ISSUE TITLE
Design update Download buttons

### ISSUE THREAD

**Issue by anistark** [anistark/qrgen#5]
- [ ] Add css and some hover effects to download buttons on `editor.html` page.
- [ ] Hide download buttons when qr image not generated.

Some design ideas: 
- https://codepen.io/andywillekens/pen/ogaLeR

**Comment by 0c0de** [comment]
Can I take it?

**Comment by anistark** [comment]
@0c0de For sure.

**Comment by 0c0de** [comment]
You have an animation when hovering over outlined buttons in bootstrap, or you mean that have to be with the link type button?

**Comment by anistark** [comment]
Yes. The link type buttons "Download as PNG" and "Download as PDF" !
